---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: conjur
  namespace: namespace-team-a
spec:
  provider:
    conjur:
      # Service URL
      url: https://conjur-follower.url
      # [OPTIONAL] base64 encoded string of certificate
      # caBundle: OPTIONALxFIELDxxxBase64xCertxString==
      caProvider:
        type: ConfigMap
        name: conjur-ca-bundle
        key: ca-bundle
        namespace: namespace-team-a
      auth:
        jwt:
          # conjur account
          account: admin
          # The authn-jwt service ID
          serviceID: k8s-workload-cluster-a
          hostId: host/teamA/OT/namespace-team-a
          # Service account to retrieve JWT token for
          serviceAccountRef:
            name: jwt-eso-service-account-namespace-team-a
            # [OPTIONAL] audiences to include in JWT token
            audiences:
              - https://conjur-cluster.url
