---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: conjur
  namespace: namespace-team-a
spec:
  refreshInterval: 10m
  secretStoreRef:
    # This name must match the metadata.name in the SecretStore
    name: conjur
    kind: SecretStore
  data:
    - secretKey: dockerhub-api-key
      remoteRef:
        key: teamA/dockerhub-api-key
    - secretKey: nexus-api-key
      remoteRef:
        key: teamA/nexus-api-key
