---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: nmatsui/hello-world-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_PASSWORD1
              valueFrom:
                secretKeyRef:
                  name: conjur
                  key: DB_PASSWORD1
