---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: conjur
spec:
  provider:
    conjur:
      # Service URL
      url: https://conjur.url
      # [OPTIONAL] base64 encoded string of certificate
      # caBundle: <ca_bundle>
      auth:
        apikey:
          # conjur account
          account: admin
          userRef:  # Get this from K8S secret
            name: conjur-creds
            key: host_id
          apiKeyRef:  # Get this from K8S secret
            name: conjur-creds
            key: host_api_key
